In [1]:
from os.path import exists
from bs4 import BeautifulSoup
import re
import requests
import time
import pandas as pd

In [2]:
zodiacs = ['aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo', 'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces']
weekday = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
subarea = ['daily','love', 'work', 'dating']

In [3]:
# scrape the horoscope from the website and save them to a csv file with two columns: horoscope and text, ignore the date
def scrape_horoscope():
    if not exists('horoscope.csv'):
        with open('horoscope.csv', 'a') as f:
            f.write(f'zodiac,area,text\n')
    for zodiac in zodiacs:
        for area in subarea:
            if area == 'daily':
                url = f'https://www.astrology.com/horoscope/daily/{zodiac}.html'
            else:
                url = f'https://www.astrology.com/horoscope/daily-{area}/{zodiac}.html'
            response = requests.get(url)
            soup = BeautifulSoup(response.text, 'html.parser')
            horoscope = soup.find('div', class_='horoscope-content-wrapper')
            text = horoscope.find(attrs={'id':'content'}).text
            with open('horoscope.csv', 'a') as f:
                f.write(f'{zodiac},{area},"{text}"\n')
            print(f'{zodiac} {area} done')
            time.sleep(1)

In [4]:
# start the program
# if not exists('horoscope.csv'):
#     scrape_horoscope()
scrape_horoscope()

aries daily done
aries love done
aries work done
aries dating done
taurus daily done
taurus love done
taurus work done
taurus dating done
gemini daily done
gemini love done
gemini work done
gemini dating done
cancer daily done
cancer love done
cancer work done
cancer dating done
leo daily done
leo love done
leo work done
leo dating done
virgo daily done
virgo love done
virgo work done
virgo dating done
libra daily done
libra love done
libra work done
libra dating done
scorpio daily done
scorpio love done
scorpio work done
scorpio dating done
sagittarius daily done
sagittarius love done
sagittarius work done
sagittarius dating done
capricorn daily done
capricorn love done
capricorn work done
capricorn dating done
aquarius daily done
aquarius love done
aquarius work done
aquarius dating done
pisces daily done
pisces love done
pisces work done
pisces dating done

In [6]:
data = pd.read_csv('horoscope.csv')
data

,zodiac,area,text,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,aries,daily,\nYou should feel grounded and connected with ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aries,love,"As the heavens turn, we watch their captivatin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aries,work,"\nRedirect your energy, Aries. You may feel in...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aries,dating,\nIt's okay to have a minor outburst every now...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,taurus,daily,\nThe moon continues its journey through your ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
69,virgo,love,"\nGet ready for gorgeous revelations today, Vi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,virgo,work,"What can you do differently, Virgo? You may ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,virgo,dating,\nIt's okay to rely on your friends for suppor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,libra,daily,\nAs the moon drifts into Gemini and the secto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,libra,love,\nOne of the most important periods of the yea...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data[["zodiac", "area", "text"]].to_csv('horoscope.csv', index=False)